CharacterId: 10009
title:
  - GroupId: 1000902
    FavorScheduleId: 100092
    CharacterId: 10009
    TextJp: すっごく美味しくなる方法
    TextCn: ''
    TextKr: ''
    TextEn: ''
    TextTh: ''
    TextTw: ''
  - GroupId: 1000903
    FavorScheduleId: 100093
    CharacterId: 10009
    TextJp: 美味しいプリン
    TextCn: ''
    TextKr: ''
    TextEn: ''
    TextTh: ''
    TextTw: ''
  - GroupId: 1000905
    FavorScheduleId: 100095
    CharacterId: 10009
    TextJp: ついつい
    TextCn: ''
    TextKr: ''
    TextEn: ''
    TextTh: ''
    TextTw: ''
content:
  - MessageGroupId: 100090010
    Id: 700
    CharacterId: 10009
    MessageCondition: FavorRankUp
    ConditionValue: 2
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100090020
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 선생님!
    MessageJP: 先生！
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100090020
    Id: 701
    CharacterId: 10009
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100090030
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ''
    MessageKR: 나 어제 책에서 굉장한 걸 읽었어!
    MessageJP: 昨日私、すごい本を読んだの！
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100090030
    Id: 702
    CharacterId: 10009
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100090040
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 굉장한 거?
    MessageJP: すごい本？
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100090040
    Id: 703
    CharacterId: 10009
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100090050
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 응! 운동선수의 자서전이었는데……..
    MessageJP: うん！アスリートの人の自伝だったんだけど……
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100090040
    Id: 704
    CharacterId: 10009
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100090050
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ''
    MessageKR: 거기에 평범한 음식을 더욱 맛있게 먹는 법이 쓰여 있던 거 있지!
    MessageJP: そこに、食べ物がすっごく美味しくなる方法が書いてあったの！
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100090050
    Id: 705
    CharacterId: 10009
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100090060
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 평범한 음식을 더욱 맛있게 먹는 법?
    MessageJP: すっごく美味しくなる方法？
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100090050
    Id: 706
    CharacterId: 10009
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100090060
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 운동선수 자서전에 왜 그런 게……?
    MessageJP: なんでアスリートの自伝にそんなことが……？
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100090060
    Id: 707
    CharacterId: 10009
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100090070
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ''
    MessageKR: 이건 미식연구회의 부원으로서 그냥 넘어갈 수 없어.
    MessageJP: これは美食研究会のメンバーとして、試さずにはいられないわね
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100090060
    Id: 708
    CharacterId: 10009
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 100092
    NextGroupId: 100090070
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 시험해보자. 선생님!
    MessageJP: 善は急げだよ、先生！
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100090070
    Id: 709
    CharacterId: 10009
    MessageCondition: FavorRankUp
    ConditionValue: 3
    PreConditionGroupId: 100090060
    PreConditionFavorScheduleId: 100092
    FavorScheduleId: 0
    NextGroupId: 100090080
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 선생님! 선생님!
    MessageJP: 先生！先生！
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100090080
    Id: 710
    CharacterId: 10009
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100090090
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ''
    MessageKR: 오늘부터 게헨나 중앙광장에서 길거리 음식 페스티벌이 열린대!
    MessageJP: 今日から中央広場で、屋台がいっぱい出店するフェスが開かれるの！
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100090090
    Id: 711
    CharacterId: 10009
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100090100
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 이즈미, 신났나 보네.
    MessageJP: そうなんだ。イズミ、すごく楽しそうだね
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100090100
    Id: 712
    CharacterId: 10009
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100090110
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 응! 나, 쭉 오늘만을 기다려 왔어!
    MessageJP: うん！私、ずっとこの日を待ってたの！
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100090100
    Id: 713
    CharacterId: 10009
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100090110
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ''
    MessageKR: 오늘은 특히 푸딩으로 엄청나게 유명한 가게가 참가하거든!
    MessageJP: 今日は特に、プリンですごく有名なあのお店が参加するし……！
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100090110
    Id: 714
    CharacterId: 10009
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 100093
    NextGroupId: 100090120
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 이건 꼭 먹어봐야 해!
    MessageJP: あれは絶対に食べないと！
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100090120
    Id: 715
    CharacterId: 10009
    MessageCondition: FavorRankUp
    ConditionValue: 5
    PreConditionGroupId: 100090110
    PreConditionFavorScheduleId: 100093
    FavorScheduleId: 0
    NextGroupId: 100090130
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 선생님! 게헨나 상점가에 라멘 가게가 새로 생긴 모양이야!
    MessageJP: 先生！ゲヘナの商店街に新しいラーメン屋ができたんだって！
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100090130
    Id: 716
    CharacterId: 10009
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100090140
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 같이 가자!
    MessageJP: 一緒に行こう！
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100090130
    Id: 717
    CharacterId: 10009
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100090140
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 사전 조사 및 정찰이야!
    MessageJP: 下見と、偵察に！
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100090140
    Id: 718
    CharacterId: 10009
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100090150
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 같은 뜻 아냐……?
    MessageJP: それ、どっちも同じ意味じゃない？
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100090150
    Id: 719
    CharacterId: 10009
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 100095
    NextGroupId: 0
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ''
    MessageKR: 어, 그런가?
    MessageJP: あれっ、そうなの？
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
