CharacterId: 10048
title:
  - GroupId: 1004802
    FavorScheduleId: 100482
    CharacterId: 10048
    TextJp: 独り立ち
    TextCn: ''
    TextKr: ''
    TextEn: ''
    TextTh: ''
    TextTw: ''
  - GroupId: 1004803
    FavorScheduleId: 100483
    CharacterId: 10048
    TextJp: 見落とし
    TextCn: ''
    TextKr: ''
    TextEn: ''
    TextTh: ''
    TextTw: ''
  - GroupId: 1004805
    FavorScheduleId: 100485
    CharacterId: 10048
    TextJp: 自責の念
    TextCn: ''
    TextKr: ''
    TextEn: ''
    TextTh: ''
    TextTw: ''
content:
  - MessageGroupId: 100480010
    Id: 100480010
    CharacterId: 10048
    MessageCondition: FavorRankUp
    ConditionValue: 2
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100480020
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 선생.
    MessageJP: 先生
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100480020
    Id: 100480020
    CharacterId: 10048
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100480030
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 앗, 사오리?! 사오리야?!
    MessageJP: サオリ！？
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100480030
    Id: 100480030
    CharacterId: 10048
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100480040
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 별일이네. 사오리가 연락을 다 주고!
    MessageJP: サオリから連絡をくれるなんて……！
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100480040
    Id: 100480040
    CharacterId: 10048
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100480050
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: …아니, 그렇게 호들갑 떨 것까진….
    MessageJP: そこまで驚くことか……
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100480040
    Id: 100480050
    CharacterId: 10048
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100480050
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 나도 선생에게 연락할 생각까진 없었지만….
    MessageJP: 私としても連絡するつもりは無かったのだが
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100480050
    Id: 100480060
    CharacterId: 10048
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100480060
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ''
    MessageKR: 아무래도… 조금 문제가 생긴 듯, 하여.
    MessageJP: 少々、問題が生じてな
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100480060
    Id: 100480070
    CharacterId: 10048
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100480070
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 문제?
    MessageJP: 問題？
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100480070
    Id: 100480080
    CharacterId: 10048
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100480080
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ''
    MessageKR: 선생이 아니면 해결할 수 없는 문제, 라고 할까.
    MessageJP: 先生でないと解決できない問題で……
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100480080
    Id: 100480090
    CharacterId: 10048
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100480090
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 염치가 없다는 건 알고 있어. 하지만….
    MessageJP: 図々しいとは百も承知だ。しかし
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100480090
    Id: 100480100
    CharacterId: 10048
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100480100
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 알았어. 지금 바로 갈게!
    MessageJP: 分かった、すぐ行く！
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100480100
    Id: 100480110
    CharacterId: 10048
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100480110
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 아… 응.
    MessageJP: ……そうか
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100480110
    Id: 100480120
    CharacterId: 10048
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 100482
    NextGroupId: 100480120
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ''
    MessageKR: …그럼, 기다리고 있겠다.
    MessageJP: では、待っている
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100480120
    Id: 100480130
    CharacterId: 10048
    MessageCondition: FavorRankUp
    ConditionValue: 3
    PreConditionGroupId: 100480110
    PreConditionFavorScheduleId: 100482
    FavorScheduleId: 0
    NextGroupId: 100480130
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 그… 선생. 오늘은, 날씨가 좋군.
    MessageJP: ……今日は、天気が良いな
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100480130
    Id: 100480140
    CharacterId: 10048
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100480140
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 어…?!
    MessageJP: ！？
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100480140
    Id: 100480150
    CharacterId: 10048
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100480150
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: …왜 그러지. 선생?
    MessageJP: どうした、先生
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100480150
    Id: 100480160
    CharacterId: 10048
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100480160
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 아니, 사오리한테서 날씨 이야기라니.
    MessageJP: サオリが、天気の話を……
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100480150
    Id: 100480170
    CharacterId: 10048
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100480160
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 완전 깜짝 놀라버렸어!
    MessageJP: びっくりした！
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100480160
    Id: 100480180
    CharacterId: 10048
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100480170
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 아니, 나라도 이 정도 안부 인사는…….
    MessageJP: ……私だって、世間話をしようと思うことはある
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100480170
    Id: 100480190
    CharacterId: 10048
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100480180
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 지난번엔 선생 도움 덕에 통장도 개설했고.
    MessageJP: 先日は、おかげで口座も作ることができた
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100480170
    Id: 100480200
    CharacterId: 10048
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100480180
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ''
    MessageKR: 덕분에 일도 시작해서, 조금은 근황을 전해둘까. 했을 뿐이다.
    MessageJP: 色々と依頼も受けるようになり、近況くらいは伝えようかと思っただけだ
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100480180
    Id: 100480210
    CharacterId: 10048
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100480190
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 뭐, 괜한 짓이었다면 그만두겠지만.
    MessageJP: 気に障ることだったら、今後は控えよう
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100480190
    Id: 100480220
    CharacterId: 10048
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100480200
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 아니아니, 전달해줘! 사오리의 근황! 최근엔 무슨 일이 있었어?!
    MessageJP: そんなこと無いよ、サオリの近況知りたい！最近はどんなことがあったの！？
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100480200
    Id: 100480230
    CharacterId: 10048
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100480210
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 호들갑은……. 아, 음. 최근엔 블랙마켓을 통해 소개받은 일을 하고 있다.
    MessageJP: 大げさだな……近頃は、ブラックマーケットで紹介された依頼をこなしている
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100480210
    Id: 100480240
    CharacterId: 10048
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100480220
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 그거 잘됐네!
    MessageJP: 良いね！
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100480220
    Id: 100480250
    CharacterId: 10048
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100480230
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: ……잘됐다, 라기엔 다소 문제가……
    MessageJP: 良い、かどうかは分からないが……
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100480230
    Id: 100480260
    CharacterId: 10048
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100480240
    FeedbackTimeMillisec: 2000
    MessageType: Text
    ImagePath: ''
    MessageKR: 아니, 아니다. 그래. 잘된 거겠지.
    MessageJP: まあ、そうだな。良いことなのかもしれない
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100480230
    Id: 100480270
    CharacterId: 10048
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100480240
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 그럼 다음에 또 기회가 되면 연락하겠어. 이만.
    MessageJP: また何かあったら連絡する
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100480240
    Id: 100480280
    CharacterId: 10048
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 100483
    NextGroupId: 100480250
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 아, 응……?
    MessageJP: あ……っ
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100480250
    Id: 100480290
    CharacterId: 10048
    MessageCondition: FavorRankUp
    ConditionValue: 5
    PreConditionGroupId: 100480240
    PreConditionFavorScheduleId: 100483
    FavorScheduleId: 0
    NextGroupId: 100480260
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 선생, 저번의 실수를 말미암아.
    MessageJP: この間のことを反省した
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100480260
    Id: 100480300
    CharacterId: 10048
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100480270
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ''
    MessageKR: 이번에 블랙마켓 은행으로부터 소개받은 일에선
    MessageJP: 今回の依頼については
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100480260
    Id: 100480310
    CharacterId: 10048
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100480270
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 확실히 계약서도 제대로 썼어.
    MessageJP: すでにきちんと契約書を書いている
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100480270
    Id: 100480320
    CharacterId: 10048
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100480280
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 그래? 잘됐네!
    MessageJP: それは良かった！
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100480280
    Id: 100480330
    CharacterId: 10048
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100480290
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 그래서 어떤 일을 구했는데?
    MessageJP: それで、今回はどんな依頼？
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100480290
    Id: 100480340
    CharacterId: 10048
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100480300
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 제법 간단한 미션이더군.
    MessageJP: 思いのほか簡単な任務だった
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100480300
    Id: 100480350
    CharacterId: 10048
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100480310
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 블랙마켓의 항쟁을 마무리하는 일이지.
    MessageJP: ブラックマーケットの抗争を終わらせるだけだ
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 100480310
    Id: 100480360
    CharacterId: 10048
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 100485
    NextGroupId: 0
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 사, 사, 사오리?!
    MessageJP: ！？
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
