CharacterId: 13002
title:
  - GroupId: 1300202
    FavorScheduleId: 130022
    CharacterId: 13002
    TextJp: ペースメーカー
    TextCn: ''
    TextKr: ''
    TextEn: ''
    TextTh: ''
    TextTw: ''
  - GroupId: 1300203
    FavorScheduleId: 130023
    CharacterId: 13002
    TextJp: ニンニク抜きだなんて
    TextCn: ''
    TextKr: ''
    TextEn: ''
    TextTh: ''
    TextTw: ''
  - GroupId: 1300205
    FavorScheduleId: 130025
    CharacterId: 13002
    TextJp: 出禁
    TextCn: ''
    TextKr: ''
    TextEn: ''
    TextTh: ''
    TextTw: ''
  - GroupId: 1300206
    FavorScheduleId: 130026
    CharacterId: 13002
    TextJp: 美食家の矜持
    TextCn: ''
    TextKr: ''
    TextEn: ''
    TextTh: ''
    TextTw: ''
content:
  - MessageGroupId: 130020010
    Id: 1223
    CharacterId: 13002
    MessageCondition: FavorRankUp
    ConditionValue: 2
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 130020020
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 문득 궁금해졌는데, 규동 가게에서는 어째서 킹 사이즈보다 큰 규동을 팔지 않는 걸까요?
    MessageJP: どうして特盛より上の大きさの牛丼は売られていないのでしょうか？
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 130020020
    Id: 1224
    CharacterId: 13002
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 130020030
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 킹 사이즈 정도면 충분히 크지 않아?
    MessageJP: 特盛で十分大きくない……？
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 130020030
    Id: 1225
    CharacterId: 13002
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 130020040
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ''
    MessageKR: 안 돼요. 킹 사이즈 한 그릇으로는 배가 충분히 차지 않는다고요.
    MessageJP: いえ、特盛一杯ではお腹いっぱいになれません
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 130020040
    Id: 1226
    CharacterId: 13002
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 130020050
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 아카리는 어째서 그렇게 한 번에 많은 음식을 먹는 거야?
    MessageJP: どうしてアカリはそんなにたくさん食べるの？
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 130020050
    Id: 1227
    CharacterId: 13002
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 130020060
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ''
    MessageKR: 후후, 우문이군요. 제가 한 번에 많은 음식을 먹는 이유는 간단하답니다.
    MessageJP: フフッ、愚問ですね。私がたくさん食べる理由は簡単です
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 130020050
    Id: 1228
    CharacterId: 13002
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 130022
    NextGroupId: 130020060
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 그 이유는…… 그곳에 음식이 있으니까!
    MessageJP: なぜなら……そこに食べ物があるからです！
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 130020060
    Id: 1229
    CharacterId: 13002
    MessageCondition: FavorRankUp
    ConditionValue: 3
    PreConditionGroupId: 130020050
    PreConditionFavorScheduleId: 130022
    FavorScheduleId: 0
    NextGroupId: 130020070
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 선생님은 어떤 라멘을 드실 때 면부터 드시나요, 아니면 국물부터 드시나요?
    MessageJP: 先生はラーメンを食べる時、麺から行きますか？それともスープからです？
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 130020070
    Id: 1230
    CharacterId: 13002
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 130020080
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 면부터 먹어.
    MessageJP: 麺からかな
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 130020070
    Id: 1231
    CharacterId: 13002
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 130020090
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 국물부터 마셔.
    MessageJP: スープからかな
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 130020080
    Id: 1232
    CharacterId: 13002
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 130020100
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ''
    MessageKR: 선생님은 라멘의 면발을 중시하는 편이시군요.
    MessageJP: なるほど、そうでしたか
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 130020090
    Id: 1233
    CharacterId: 13002
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 130020100
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ''
    MessageKR: 선생님은 라멘의 국물을 중시하는 편이시군요.
    MessageJP: なるほど、そうでしたか
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 130020100
    Id: 1234
    CharacterId: 13002
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 130020110
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 저는 국물부터 마시는 걸 선호해요.
    MessageJP: 個人的にはスープ一択ですね
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 130020100
    Id: 1235
    CharacterId: 13002
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 130020110
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ''
    MessageKR: 진한 국물이야말로 라멘의 맛이 모두 담긴 정수라 할 수 있으니까요.
    MessageJP: スープこそ、ラーメンの全てが詰まった精髄と言っても過言ではありません
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 130020110
    Id: 1236
    CharacterId: 13002
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 130020120
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ''
    MessageKR: 거기에 으깬 마늘의 알싸한 맛을 더하면…… 정말 참을 수가 없어요!
    MessageJP: そこにすり潰したニンニクが加わった日には……ああ、なんて素晴らしい！
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 130020120
    Id: 1237
    CharacterId: 13002
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 130023
    NextGroupId: 130020130
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 어쩐지 아저씨 같은 취향인걸…….
    MessageJP: なんだか、おじさんみたいな好みだね……
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 130020130
    Id: 1238
    CharacterId: 13002
    MessageCondition: FavorRankUp
    ConditionValue: 5
    PreConditionGroupId: 130020120
    PreConditionFavorScheduleId: 130023
    FavorScheduleId: 0
    NextGroupId: 130020140
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 무한리필은 정말 멋진 문화인 것 같아요.
    MessageJP: 食べ放題というのは、本当に素敵な文化だと思います
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 130020140
    Id: 1239
    CharacterId: 13002
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 130020150
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ''
    MessageKR: 가격에 구애받지 않고 원하는 음식을 원하는 만큼 먹을 수 있다니…….
    MessageJP: 一定の価格で、食べたいものを好きなだけ食べられるなんて……
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 130020140
    Id: 1240
    CharacterId: 13002
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 130020150
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ''
    MessageKR: 이 아이디어를 낸 사람은 천재(天才)일 게 분명해요!
    MessageJP: このアイデアを出した方は、天才に違いありません！
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 130020150
    Id: 1241
    CharacterId: 13002
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 130025
    NextGroupId: 130020160
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 어제 아카리가 방문한 무한리필 가게 주인으로서는 천재(天災)였겠지만…….
    MessageJP: アカリをお客さんとして迎える側にとっては天災だね……
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 130020160
    Id: 1242
    CharacterId: 13002
    MessageCondition: FavorRankUp
    ConditionValue: 6
    PreConditionGroupId: 130020150
    PreConditionFavorScheduleId: 130025
    FavorScheduleId: 0
    NextGroupId: 130020170
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 다음 대식 대회의 대결 종목은 <카레 많이 먹기>로 정해진 모양이에요.
    MessageJP: 次の大食い大会の種目は、「カレー」に決まったそうです
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 130020170
    Id: 1243
    CharacterId: 13002
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 130020180
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ''
    MessageKR: 카레는 조금 자신 없는데…… 미리 연습을 해두어야겠어요.
    MessageJP: カレー……ちょっと自信がないので、前もって特訓しておかないとです
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 130020180
    Id: 1244
    CharacterId: 13002
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 130020190
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 아카리도 가리는 음식이 있어?
    MessageJP: アカリにも苦手な食べ物があるんだ？
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 130020190
    Id: 1245
    CharacterId: 13002
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 130020200
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ''
    MessageKR: 못 먹는 건 아니지만 많이 먹기 힘든 음식은 있어요.
    MessageJP: 食べられはするのですが、大食いにはちょっと……というものはあります
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 130020200
    Id: 1246
    CharacterId: 13002
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 130020210
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ''
    MessageKR: 예를 들자면 아까 말했던 카레처럼 매운 음식은 자꾸 물을 마시게 되어서 배가 빨리 차거든요.
    MessageJP: 例えばカレーですと、途中に何度もお水を飲んでしまうので……
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 130020200
    Id: 1247
    CharacterId: 13002
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 130020210
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ''
    MessageKR: 대신 초밥처럼 개인적으로 좋아하는 음식은 다른 음식보다 두 배는 더 먹을 수 있어요.
    MessageJP: 逆にお寿司なんかは、私が好きなこともあって他の倍くらい食べられます
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 130020210
    Id: 1248
    CharacterId: 13002
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 130026
    NextGroupId: 0
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 대식가라고 해서 기호가 없는 건 아니랍니다!
    MessageJP: 大食いだからといって、好き嫌いがないわけではないんですよ
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
