CharacterId: 16010
title:
  - GroupId: 1601002
    FavorScheduleId: 160102
    CharacterId: 16010
    TextJp: マイスターの密やかな趣味
    TextCn: ''
    TextKr: ''
    TextEn: ''
    TextTh: ''
    TextTw: ''
  - GroupId: 1601003
    FavorScheduleId: 160103
    CharacterId: 16010
    TextJp: マイスターの熱烈な応援
    TextCn: ''
    TextKr: ''
    TextEn: ''
    TextTh: ''
    TextTw: ''
  - GroupId: 1601005
    FavorScheduleId: 160105
    CharacterId: 16010
    TextJp: マイスターの殺伐とした応援
    TextCn: ''
    TextKr: ''
    TextEn: ''
    TextTh: ''
    TextTw: ''
  - GroupId: 1601006
    FavorScheduleId: 160106
    CharacterId: 16010
    TextJp: マイスターの優しい子守唄
    TextCn: ''
    TextKr: ''
    TextEn: ''
    TextTh: ''
    TextTw: ''
content:
  - MessageGroupId: 160100010
    Id: 160100010
    CharacterId: 16010
    MessageCondition: FavorRankUp
    ConditionValue: 2
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 160100020
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 선생님은 주말에 보통 무얼 하면서 시간을 보내?
    MessageJP: 先生は休日に何をして過ごすことが多いの？
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 160100020
    Id: 160100020
    CharacterId: 16010
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 160100030
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 아무것도 안 하는데……
    MessageJP: 何もしてないかな……
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 160100020
    Id: 160100030
    CharacterId: 16010
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 160100040
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 밀린 잔업을 하면서 보내.
    MessageJP: 溜まった書類仕事と戦ってるよ
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 160100030
    Id: 160100040
    CharacterId: 16010
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 160100050
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 휴식도 중요한 일과 중 하나지.
    MessageJP: たしかに身体を休めるのも大切だよね
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 160100030
    Id: 160100050
    CharacterId: 16010
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 160100050
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ''
    MessageKR: 선생님이 제대로 휴일을 즐기고 있는 것 같아서 다행이야.
    MessageJP: 先生が休日を楽しんでるみたいで良かった
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 160100040
    Id: 160100060
    CharacterId: 16010
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 160100050
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ''
    MessageKR: ……너무 무리하는 거 아냐?
    MessageJP: ……無理しすぎじゃない？
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 160100040
    Id: 160100070
    CharacterId: 16010
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 160100050
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 휴식 없이 연달아 일하는 건 오히려 더 비효율적일 수도 있어.
    MessageJP: 休みなしに働き続けるのは、却って非効率的だよ
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 160100050
    Id: 160100080
    CharacterId: 16010
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 160100060
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 히비키는 주말을 어떻게 보내?
    MessageJP: そういうヒビキは？
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 160100060
    Id: 160100090
    CharacterId: 16010
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 160100070
    FeedbackTimeMillisec: 500
    MessageType: Text
    ImagePath: ''
    MessageKR: ……나 말이야?
    MessageJP: ……私？
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 160100070
    Id: 160100100
    CharacterId: 16010
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 160100080
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 내가 주말에 하는 일이라면……
    MessageJP: うーん、私はどうだろ……
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 160100080
    Id: 160100110
    CharacterId: 16010
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 160102
    NextGroupId: 160100090
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ''
    MessageKR: 역시 무언가를 만드는 것이려나.
    MessageJP: だいたい何かを作ってるよ
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 160100090
    Id: 160100120
    CharacterId: 16010
    MessageCondition: FavorRankUp
    ConditionValue: 3
    PreConditionGroupId: 160100080
    PreConditionFavorScheduleId: 160102
    FavorScheduleId: 0
    NextGroupId: 160100100
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: ……선생님, 그 소식 들었어.
    MessageJP: ……先生、大丈夫？例の話を聞いたんだけど
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 160100100
    Id: 160100130
    CharacterId: 16010
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 160100110
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 샬레에 갑작스러운 정전이 일어나는 바람에
    MessageJP: シャーレで突然停電が起こったせいで
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 160100100
    Id: 160100140
    CharacterId: 16010
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 160100110
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 하루종일 처리한 작업물이 날아갔다며
    MessageJP: 一日かけた作業データが吹っ飛んだって……
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 160100100
    Id: 160100150
    CharacterId: 16010
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 160100110
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 어떻게 복구할 수 있는 방법은 없는 거야……?
    MessageJP: どうにか復旧する方法はないの……？
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 160100110
    Id: 160100160
    CharacterId: 16010
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 160100120
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 베리타스의 학생들도 복구는 어렵대…….
    MessageJP: ヴェリタスに頼ったけど、復旧は難しいだろうって……
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 160100120
    Id: 160100170
    CharacterId: 16010
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 160100130
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ''
    MessageKR: 그렇다면 내가 할 수 있는 일은 없겠지만……
    MessageJP: なら私にできることはないか……
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 160100120
    Id: 160100180
    CharacterId: 16010
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 160100130
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 그래도 뭔가 도울 수 있는 게 없을까
    MessageJP: ……でも、何か力になれないかな？
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 160100130
    Id: 160100190
    CharacterId: 16010
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 160100140
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 지금 필요한 건 응원뿐이야.
    MessageJP: 応援してくれるとうれしいな
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 160100140
    Id: 160100200
    CharacterId: 16010
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 160100150
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ''
    MessageKR: 응원이라…….
    MessageJP: 応援……
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 160100150
    Id: 160100210
    CharacterId: 16010
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 160100160
    FeedbackTimeMillisec: 500
    MessageType: Text
    ImagePath: ''
    MessageKR: 알겠어.
    MessageJP: うん、分かった
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 160100150
    Id: 160100220
    CharacterId: 16010
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 160103
    NextGroupId: 160100160
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 힘내, 선생님.
    MessageJP: 頑張ってね、先生
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 160100160
    Id: 160100230
    CharacterId: 16010
    MessageCondition: FavorRankUp
    ConditionValue: 5
    PreConditionGroupId: 160100150
    PreConditionFavorScheduleId: 160103
    FavorScheduleId: 0
    NextGroupId: 160100170
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: ……지난번의 사건 이후로 많은 고민을 했어.
    MessageJP: ……この前の出来事があってから、たくさん悩んだの
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 160100170
    Id: 160100240
    CharacterId: 16010
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 160100180
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 실내에서 일하는 사람들의 의욕을 높일 수 있는 응원 도구는 없을까— 하고.
    MessageJP: デスクワークの意欲を高められる応援道具は何かなって
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 160100170
    Id: 160100250
    CharacterId: 16010
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 160100180
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: ……그리고 오랜 고민 끝에 시제품을 만드는 데 성공했어.
    MessageJP: ……試行錯誤を重ねて、ようやく試作品ができたんだ
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 160100180
    Id: 160100260
    CharacterId: 16010
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 160100190
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 사무직 근무자를 위한 궁극의 응원 도구.
    MessageJP: これはデスクワーカーにとって究極の応援道具
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 160100190
    Id: 160100270
    CharacterId: 16010
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 160100200
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: ……다음 당번 때 시험 삼아 들고 갈게.
    MessageJP: ……次の当番の日、試しに持っていくね
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 160100200
    Id: 160100280
    CharacterId: 16010
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 160105
    NextGroupId: 160100210
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: ……뭘 만든 거야?
    MessageJP: ……一体何を作ったの？
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 160100210
    Id: 160100290
    CharacterId: 16010
    MessageCondition: FavorRankUp
    ConditionValue: 6
    PreConditionGroupId: 160100200
    PreConditionFavorScheduleId: 160105
    FavorScheduleId: 0
    NextGroupId: 160100220
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 지난번에 만든 응원 도구는 꽤 괜찮았다고 생각했는데……
    MessageJP: この前の応援道具は結構良かったと思うんだけど……
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 160100220
    Id: 160100300
    CharacterId: 16010
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 160100230
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 하지만 선생님이 싫어하는 것 같으니 어쩔 수 없지.
    MessageJP: でも先生は嫌みたいだし、仕方ない
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 160100220
    Id: 160100310
    CharacterId: 16010
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 160100230
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 우수한 마이스터라면 언제나 클라이언트의 의견을 귀담아들어야 하니까.
    MessageJP: 優秀なマイスターなら、常にクライアントの意見に耳を傾けるべきだもんね
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 160100230
    Id: 160100320
    CharacterId: 16010
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 160100240
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 그래서 고민 끝에 새로운 응원 도구를 완성했어.
    MessageJP: 今度は別の応援道具を用意してみたよ
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 160100230
    Id: 160100330
    CharacterId: 16010
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 160100240
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ''
    MessageKR: ……다음번에 샬레에 가게 되면 보여 줄게.
    MessageJP: 今度シャーレに行くことがあれば、持っていくね
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 160100240
    Id: 160100340
    CharacterId: 16010
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 160100250
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 자폭 기능이 포함된 건 아니지?
    MessageJP: 今度は自爆しないよね？
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 160100250
    Id: 160100350
    CharacterId: 16010
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 160100260
    FeedbackTimeMillisec: 2000
    MessageType: Text
    ImagePath: ''
    MessageKR: ……
    MessageJP: ……
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 160100260
    Id: 160100360
    CharacterId: 16010
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 160100270
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: ……직접 가서 보여 줄게.
    MessageJP: ……やっぱり、これからそっちに向かおうかな
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 160100270
    Id: 160100370
    CharacterId: 16010
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 160106
    NextGroupId: 0
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 자폭 기능이 포함된 건 아니지?!
    MessageJP: 本当に自爆しないよね！？
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
