CharacterId: 20006
title:
  - GroupId: 2000602
    FavorScheduleId: 200062
    CharacterId: 20006
    TextJp: 天才のコツ
    TextCn: ''
    TextKr: ''
    TextEn: ''
    TextTh: ''
    TextTw: ''
  - GroupId: 2000603
    FavorScheduleId: 200063
    CharacterId: 20006
    TextJp: 天才の休日
    TextCn: ''
    TextKr: ''
    TextEn: ''
    TextTh: ''
    TextTw: ''
  - GroupId: 2000605
    FavorScheduleId: 200065
    CharacterId: 20006
    TextJp: サヤのおいしいレストラン
    TextCn: ''
    TextKr: ''
    TextEn: ''
    TextTh: ''
    TextTw: ''
  - GroupId: 2000606
    FavorScheduleId: 200066
    CharacterId: 20006
    TextJp: 流れ行くもの
    TextCn: ''
    TextKr: ''
    TextEn: ''
    TextTh: ''
    TextTw: ''
content:
  - MessageGroupId: 200060010
    Id: 200060010
    CharacterId: 20006
    MessageCondition: FavorRankUp
    ConditionValue: 2
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200060020
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 선생, 이번 주 휴일에 시간 괜찮아?
    MessageJP: 先生、今週末は時間ある？
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 200060020
    Id: 200060020
    CharacterId: 20006
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200060030
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 또 이상한 약을 먹이려는 거야?
    MessageJP: 今度は何の実験？
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 200060020
    Id: 200060030
    CharacterId: 20006
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200060030
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 이번 주말은 봐줘…….
    MessageJP: 変な薬はそろそろ勘弁……
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 200060030
    Id: 200060040
    CharacterId: 20006
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200060040
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 그런 거 아니거든!
    MessageJP: 違う違う、そういうのじゃないのだ！
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 200060040
    Id: 200060050
    CharacterId: 20006
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200060050
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ''
    MessageKR: 전에 선생이 가고 싶다고 했던 중화요리집이 이번 주말부터 신메뉴를 내놓는다고 해서 알려주려 했던 것이다!
    MessageJP: この前先生が言ってた中華料理屋で新メニューが出るって聞いて、教えようと思っただけなのに！
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 200060040
    Id: 200060060
    CharacterId: 20006
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200060050
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 모처럼 신경을 써 주었더니, 나님의 호의를 그런 눈으로 보다니……
    MessageJP: 全部の用事が実験だと思われるのは心外なのだ！
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 200060050
    Id: 200060070
    CharacterId: 20006
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200060060
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 미안. 이번 휴일은 시간 괜찮아.
    MessageJP: ごめんごめん、じゃあお詫びってわけでもないけど
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 200060060
    Id: 200060080
    CharacterId: 20006
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200060070
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 대신 사과의 의미로 내가 한턱 낼게.
    MessageJP: 奢るよ、一緒に行こう
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 200060070
    Id: 200060090
    CharacterId: 20006
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200060080
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 정말? 그 말, 잊으면 안 되는 것이다!
    MessageJP: 本当か！もう今さら撤回は無しだぞ！？
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 200060070
    Id: 200060100
    CharacterId: 20006
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 200062
    NextGroupId: 200060080
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 그럼 이번 주말에 전에 말했던 가게 앞에서 보자!
    MessageJP: じゃあ今週末、お店の前で待ち合わせなのだ！
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 200060080
    Id: 200060110
    CharacterId: 20006
    MessageCondition: FavorRankUp
    ConditionValue: 3
    PreConditionGroupId: 200060070
    PreConditionFavorScheduleId: 200062
    FavorScheduleId: 0
    NextGroupId: 200060090
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 후우…… 천재의 삶이란 정말 고독한 것이다.
    MessageJP: 天才は孤独なのだ……
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 200060090
    Id: 200060120
    CharacterId: 20006
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200060100
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 아무리 설명하려 해도 범인들은 이해해 주질 않으니…….
    MessageJP: いくら説明しても、理解されない……
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 200060100
    Id: 200060130
    CharacterId: 20006
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200060110
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 무슨 문제라도 있어?
    MessageJP: 何かあったの？
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 200060110
    Id: 200060140
    CharacterId: 20006
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200060120
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ''
    MessageKR: 어, 그러니까…….
    MessageJP: あ、そうだ、先生
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 200060110
    Id: 200060150
    CharacterId: 20006
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200060120
    FeedbackTimeMillisec: 500
    MessageType: Text
    ImagePath: ''
    MessageKR: 아니, 아무것도 아니다!
    MessageJP: い、いや、何でもないのだ！
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 200060120
    Id: 200060160
    CharacterId: 20006
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200060130
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 나님 혼자서도 충분히 해결할 수 있는 문제인 것이다!
    MessageJP: ぼく様だけでも、十分解決できる問題なのだ！
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 200060120
    Id: 200060170
    CharacterId: 20006
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200060130
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ''
    MessageKR: 산해경 제일의 수재인 나님에게 불가능이란 없으니까! 음-하-하-핫!
    MessageJP: この山海経随一の天才であるぼく様に、不可能なんて無いからな！うーはっはっはっ！
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 200060130
    Id: 200060180
    CharacterId: 20006
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 200063
    NextGroupId: 200060140
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: ……뭔가 수상한데.
    MessageJP: ……？
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 200060140
    Id: 200060190
    CharacterId: 20006
    MessageCondition: FavorRankUp
    ConditionValue: 5
    PreConditionGroupId: 200060130
    PreConditionFavorScheduleId: 200063
    FavorScheduleId: 0
    NextGroupId: 200060150
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 선생. 지난번에는 한정 메뉴 사는 걸 도와줘서 고마웠던 것이다.
    MessageJP: 先生、この間のケーキの件はありがとうなのだ
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 200060150
    Id: 200060200
    CharacterId: 20006
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200060160
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 답례의 의미로 이번에는 나님이 현무상회에서 맛있는 음식을 살게.
    MessageJP: お返しに、今度はぼく様が何か玄武商会で美味しいものを奢ってあげる！
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 200060150
    Id: 200060210
    CharacterId: 20006
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200060160
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 선생은 뭐가 먹고 싶은 것이냐?
    MessageJP: 先生は何か食べたいものとかあるか？
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 200060160
    Id: 200060220
    CharacterId: 20006
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200060170
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 볶음밥이 좋겠어.
    MessageJP: チャーハンの気分！
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 200060160
    Id: 200060230
    CharacterId: 20006
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200060170
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 야키소바가 먹고 싶어!
    MessageJP: 焼きそばの気分！
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 200060170
    Id: 200060240
    CharacterId: 20006
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200060180
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ''
    MessageKR: 아, 그러고 보니 이번 주는 현무상회의 가게들이 새로 개발한 라멘 메뉴를 내놓는 라멘 주간인데…
    MessageJP: あ、そういえば今週は、玄武商会のお店が次々に新しいラーメンを出す「ラーメン週間」だったのだ！
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 200060170
    Id: 200060250
    CharacterId: 20006
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200060180
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ''
    MessageKR: 선생! 이번 휴일은 현무상회에서 함께 라멘을 먹는 것이다!
    MessageJP: 先生！ちょうどぼく様おすすめのお店があるから、そこに行こう！
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 200060180
    Id: 200060260
    CharacterId: 20006
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 200065
    NextGroupId: 200060190
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: ……내 의견은 왜 물어본 거야?
    MessageJP: 私の意見を聞いた意味は……？
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 200060190
    Id: 200060270
    CharacterId: 20006
    MessageCondition: FavorRankUp
    ConditionValue: 6
    PreConditionGroupId: 200060180
    PreConditionFavorScheduleId: 200065
    FavorScheduleId: 0
    NextGroupId: 200060200
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 으으, 으으으…….
    MessageJP: 参ったのだ……
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 200060200
    Id: 200060280
    CharacterId: 20006
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200060210
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 무슨 문제라도 있어?
    MessageJP: どうしたの？
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 200060210
    Id: 200060290
    CharacterId: 20006
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200060220
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ''
    MessageKR: 지난번에 개발한 특제 매운 소스가 생각 외로 큰 인기를 끄는 바람에……
    MessageJP: この前開発した特製の激辛ソースが、思った以上に大人気で……
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 200060210
    Id: 200060300
    CharacterId: 20006
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200060220
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 특제 소스를 만드느라 연구할 시간이 부족해진 것이다……
    MessageJP: そっちに時間を取られて、研究に手が回らないのだ
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 200060210
    Id: 200060310
    CharacterId: 20006
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200060220
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 정말이지, 다들 연단방을 무어라고 생각하는 것이냐?
    MessageJP: 全く……
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 200060220
    Id: 200060320
    CharacterId: 20006
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200060230
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ''
    MessageKR: 연단방은 불로불사의 영약을 만드는 곳이지, 소스를 만드는 곳이 아니라고!
    MessageJP: 錬丹術研究会はあくまで「不老不死の霊薬を作ること」を目的とした場所であって、ソースを作る場所じゃないのだ！
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 200060220
    Id: 200060330
    CharacterId: 20006
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200060230
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 너무 바쁘다 보니 최근에는 네즈스케의 손이라도 빌리고 싶어질 정도니……
    MessageJP: もうネズ助の手も借りたいぐらい……
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 200060230
    Id: 200060340
    CharacterId: 20006
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200060240
    FeedbackTimeMillisec: 2500
    MessageType: Text
    ImagePath: ''
    MessageKR: 잠깐. 만약 그 방법을 사용하면…….
    MessageJP: 良いことを思いついた！
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 200060240
    Id: 200060350
    CharacterId: 20006
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200060250
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 안 돼.
    MessageJP: やめておこう
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 200060250
    Id: 200060360
    CharacterId: 20006
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200060260
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 응? 나님은 아직 아무 말도 하지 않았다만.
    MessageJP: ぼく様まだ何も言ってないのに！？
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 200060260
    Id: 200060370
    CharacterId: 20006
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200060270
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 무얼 하려는지는 모르겠지만 안 돼.
    MessageJP: なんか嫌な予感がするし……
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 200060270
    Id: 200060380
    CharacterId: 20006
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 200066
    NextGroupId: 0
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 쳇, 눈치 하난 빠르긴…….
    MessageJP: ぐっ、仕方ない……おとなしくソースを作るのだ……
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
