CharacterId: 20004
title:
  - GroupId: 2000402
    FavorScheduleId: 200042
    CharacterId: 20004
    TextJp: 可愛いは正義
    TextCn: ''
    TextKr: ''
    TextEn: ''
    TextTh: ''
    TextTw: ''
  - GroupId: 2000403
    FavorScheduleId: 200043
    CharacterId: 20004
    TextJp: 海辺の[ruby=スナイパー]狙撃手[/ruby]
    TextCn: ''
    TextKr: ''
    TextEn: ''
    TextTh: ''
    TextTw: ''
  - GroupId: 2000405
    FavorScheduleId: 200045
    CharacterId: 20004
    TextJp: 熱中症対策
    TextCn: ''
    TextKr: ''
    TextEn: ''
    TextTh: ''
    TextTw: ''
  - GroupId: 2000406
    FavorScheduleId: 200046
    CharacterId: 20004
    TextJp: 狙撃手と煙は高いところが好き
    TextCn: ''
    TextKr: ''
    TextEn: ''
    TextTh: ''
    TextTw: ''
content:
  - MessageGroupId: 20004010
    Id: 20004010
    CharacterId: 20004
    MessageCondition: FavorRankUp
    ConditionValue: 2
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 20004020
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 선생님, 오후에 시내에서 잠깐 어울려 주실 수 있나요?
    MessageJP: 先生。今日の午後、少し付き合っていただけないでしょうか？
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 20004020
    Id: 20004020
    CharacterId: 20004
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 20004030
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 다름이 아니라 이번 하계 훈련에 사용할 새 수영복을 사려고 해서요.
    MessageJP: 実は今度の訓練で使う、新しい水着を買おうと思っていまして。アドバイスを頂けないかなと
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 20004030
    Id: 20004030
    CharacterId: 20004
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 20004040
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 상관없지만……
    MessageJP: えっと、付き合ってあげたい気持ちはやまやまなんだけど……
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 20004040
    Id: 20004040
    CharacterId: 20004
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 20004050
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 친구가 아니라 나랑 가도 괜찮아?
    MessageJP: お友達とかじゃなくて、私で大丈夫？
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 20004050
    Id: 20004050
    CharacterId: 20004
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 20004060
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 중학교 때부터 입던 수영복이 있기는 하지만 더 입기에는 작아진 것 같아서요.
    MessageJP: はい、ぜひ先生にお願いできればと。その、実は、中学校の時まで着ていた水着はあるのですが、少しきつくなってしまいまして……
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 20004050
    Id: 20004060
    CharacterId: 20004
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 20004060
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ''
    MessageKR: 모처럼 정의실현부에 들어왔으니 다른 부원, 선배 여러분께 부끄럽지 않을 멋진 수영복을 새로 갖고 싶습니다.
    MessageJP: せっかくなので正義実現委員会として、もっと相応しい水着が欲しいなと思っているんです
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 20004060
    Id: 20004070
    CharacterId: 20004
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 20004070
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 멋진 수영복을 찾을 수 있으면 좋겠네.
    MessageJP: そ、そっか……
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 20004070
    Id: 20004080
    CharacterId: 20004
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 20004080
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 네, 그러기 위해서는 선생님의 도움이 필요합니다.
    MessageJP: はい、そのためにも先生のお力をお借りしたく
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 20004070
    Id: 20004090
    CharacterId: 20004
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 200042
    NextGroupId: 20004080
    FeedbackTimeMillisec: 2500
    MessageType: Text
    ImagePath: ''
    MessageKR: 그럼 매장에서 먼저 기다리고 있겠습니다.
    MessageJP: では、お待ちしておりますね
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 20004080
    Id: 20004100
    CharacterId: 20004
    MessageCondition: FavorRankUp
    ConditionValue: 3
    PreConditionGroupId: 20004070
    PreConditionFavorScheduleId: 200042
    FavorScheduleId: 0
    NextGroupId: 20004090
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 선생님, 지금 바로 이 앞의 해변으로 나와주실 수 있으신가요?
    MessageJP: 先生、今から海辺の方まで来ていただけますか？
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 20004090
    Id: 20004110
    CharacterId: 20004
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 20004100
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 선생님께 보여드리고 싶은 옷이 있습니다.
    MessageJP: 先生にお見せしたいものがありまして
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 20004100
    Id: 20004120
    CharacterId: 20004
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 20004110
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 수영복 말이지?
    MessageJP: うん、すぐ向かうね
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 20004110
    Id: 20004130
    CharacterId: 20004
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 20004120
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ''
    MessageKR: 전에 구입한 이후로 입어볼 기회가 통 없었는데, 마침 여름 훈련을 나온 참에 입어보았습니다.
    MessageJP: この前買ってから着る機会が無かったのですが、せっかくの海辺ですし
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 20004110
    Id: 20004140
    CharacterId: 20004
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 20004120
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 이 옷은 백사장에서만 입을 수 있는 옷이니까요.
    MessageJP: そもそも、こういうところでしかあまり着られないので
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 20004120
    Id: 20004150
    CharacterId: 20004
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 20004130
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 수영복 말이지……?
    MessageJP: この間買った水着の話？
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 20004130
    Id: 20004160
    CharacterId: 20004
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 20004140
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 하지만 가급적 빨리 와주실 수 있겠습니까?
    MessageJP: あ、できれば少し早めに来ていただけると助かります
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 20004140
    Id: 20004170
    CharacterId: 20004
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 20004150
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ''
    MessageKR: 이 옷을 입고 백사장 한가운데에서 기다리는 건 꽤나 고된 일이므로……
    MessageJP: これを着た状態で待っているのはその、少々……
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 20004150
    Id: 20004180
    CharacterId: 20004
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 200043
    NextGroupId: 20004160
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 수영복 이야기하는 거 맞지?!
    MessageJP: え、水着じゃないの！？一体何を着てるの！？
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 20004160
    Id: 20004190
    CharacterId: 20004
    MessageCondition: FavorRankUp
    ConditionValue: 5
    PreConditionGroupId: 20004150
    PreConditionFavorScheduleId: 200043
    FavorScheduleId: 0
    NextGroupId: 20004170
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 선생님, 전에 말씀드린 수영 훈련을 오늘 오후에 진행하려 합니다.
    MessageJP: 先生。体調も回復しましたので、以前お話した通り、まずは少し水泳でもしてみようかと
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 20004170
    Id: 20004200
    CharacterId: 20004
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 20004180
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 마시로가 걱정되니 이번에도 따라갈게.
    MessageJP: じゃあ、私もそっちに向かうね
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 20004180
    Id: 20004210
    CharacterId: 20004
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 20004190
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 오시는 건 상관없습니다만……
    MessageJP: えっと、お越しいただけるのは嬉しいのですが……
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 20004180
    Id: 20004220
    CharacterId: 20004
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 20004190
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 이번 훈련은 물 위에서 하는 훈련이니 열사병으로 쓰러지는 일은 없을 겁니다.
    MessageJP: 今回はただの水泳ですし、そこまでご心配いただかなくても大丈夫ですよ……？
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 20004190
    Id: 20004230
    CharacterId: 20004
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 20004200
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ''
    MessageKR: 다만 수영을 하기 전에 백사장 위에서 가벼운 준비운동을 할까 하는데…… 이 정도는 괜찮겠지요?
    MessageJP: 泳ぐ前に、浜辺で簡単な準備運動をするくらいで……
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 20004200
    Id: 20004240
    CharacterId: 20004
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 20004210
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 물론이지.
    MessageJP: 念には念をってことで。私も付き合うよ
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 20004200
    Id: 20004250
    CharacterId: 20004
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 20004210
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 수영 전의 준비운동은 중요하니까.
    MessageJP: それにマシロが泳ぐところを見たいなって
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 20004210
    Id: 20004260
    CharacterId: 20004
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 20004220
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 이해해 주셔서 감사합니다.
    MessageJP: な、なるほど……そういうことでしたか
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 20004210
    Id: 20004270
    CharacterId: 20004
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 200045
    NextGroupId: 20004220
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 그럼 해수욕장에서 뵙겠습니다!
    MessageJP: では、お待ちしてますね
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 20004220
    Id: 20004280
    CharacterId: 20004
    MessageCondition: FavorRankUp
    ConditionValue: 6
    PreConditionGroupId: 20004210
    PreConditionFavorScheduleId: 200045
    FavorScheduleId: 0
    NextGroupId: 20004230
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 어제는 수고 많으셨습니다, 선생님.
    MessageJP: 昨日はお疲れ様でした、先生
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 20004230
    Id: 20004290
    CharacterId: 20004
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 20004240
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 마시로는 오늘도 훈련하러 나가는 거야?
    MessageJP: お疲れ様。マシロは今日も訓練？
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 20004240
    Id: 20004300
    CharacterId: 20004
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 20004250
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 아뇨, 오늘은 훈련 대신 해변에서 봉사활동을 할 계획입니다.
    MessageJP: いえ、今日は訓練ではなくボランティア活動をする予定です
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 20004250
    Id: 20004310
    CharacterId: 20004
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 20004260
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 봉사활동?
    MessageJP: ボランティア活動？
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 20004260
    Id: 20004320
    CharacterId: 20004
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 20004270
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ''
    MessageKR: 예, 이곳 해변에도 도움의 손길을 기다리고 있는 일은 잔뜩 있으니까요.
    MessageJP: はい、色々と助けが必要だと聞きまして
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 20004260
    Id: 20004330
    CharacterId: 20004
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 20004270
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 쓰레기 치우기부터 길 잃은 미아를 보호하는 일까지……
    MessageJP: ゴミ拾いや迷子の保護など、海辺にはトラブルがたくさんありますから
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 20004270
    Id: 20004340
    CharacterId: 20004
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 20004280
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 휴양지에서까지 고생이 많네.
    MessageJP: マシロは偉いね
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 20004280
    Id: 20004350
    CharacterId: 20004
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 0
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 아뇨, 제게는 그다지 수고스러운 일도 아닙니다.
    MessageJP: いえいえ、大したことでは
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 20004280
    Id: 20004360
    CharacterId: 20004
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 200046
    NextGroupId: 0
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 이 또한 정의를 위한 일이니까요!
    MessageJP: これもまた、正義のための行いですので！
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
