CharacterId: 20016
title:
  - GroupId: 2001602
    FavorScheduleId: 200162
    CharacterId: 20016
    TextJp: '襲来するフロイライン '
    TextCn: ''
    TextKr: ''
    TextEn: ''
    TextTh: ''
    TextTw: ''
  - GroupId: 2001603
    FavorScheduleId: 200163
    CharacterId: 20016
    TextJp: 誘惑するフロイライン
    TextCn: ''
    TextKr: ''
    TextEn: ''
    TextTh: ''
    TextTw: ''
  - GroupId: 2001605
    FavorScheduleId: 200165
    CharacterId: 20016
    TextJp: 狡猾なフロイライン
    TextCn: ''
    TextKr: ''
    TextEn: ''
    TextTh: ''
    TextTw: ''
  - GroupId: 2001606
    FavorScheduleId: 200166
    CharacterId: 20016
    TextJp: 微笑みのフロイライン
    TextCn: ''
    TextKr: ''
    TextEn: ''
    TextTh: ''
    TextTw: ''
content:
  - MessageGroupId: 200160010
    Id: 200160010
    CharacterId: 20016
    MessageCondition: FavorRankUp
    ConditionValue: 2
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200160020
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 선생님, 샬레에 계신가요?
    MessageJP: 先生、今はシャーレにいるんですか？
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 200160020
    Id: 200160020
    CharacterId: 20016
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200160030
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 아, 이로하. 일단은 그런데. 왜?
    MessageJP: うん、そうだよ。どうしたの？
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 200160030
    Id: 200160030
    CharacterId: 20016
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200160040
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 그럼 됐습니다.
    MessageJP: そうですか
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 200160040
    Id: 200160040
    CharacterId: 20016
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 200162
    NextGroupId: 200160050
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: …이로하? 응?
    MessageJP: ……イロハ？
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 200160050
    Id: 200160050
    CharacterId: 20016
    MessageCondition: FavorRankUp
    ConditionValue: 3
    PreConditionGroupId: 200160040
    PreConditionFavorScheduleId: 200162
    FavorScheduleId: 0
    NextGroupId: 200160060
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 오늘도 그럼 땡땡이치러….
    MessageJP: それでは今日もサボりに
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 200160060
    Id: 200160060
    CharacterId: 20016
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200160070
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 가 아니라, 업무차 찾아뵙도록 하겠습니다.
    MessageJP: ではなく、お仕事のことでお伺いしますね
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 200160070
    Id: 200160070
    CharacterId: 20016
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 200163
    NextGroupId: 200160080
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: …땡땡이? 응?
    MessageJP: ……イロハさん、隠す気ないですよね？
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 200160080
    Id: 200160080
    CharacterId: 20016
    MessageCondition: FavorRankUp
    ConditionValue: 5
    PreConditionGroupId: 200160070
    PreConditionFavorScheduleId: 200163
    FavorScheduleId: 0
    NextGroupId: 200160090
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 선생님, 오늘 일정은 어떠신가요?
    MessageJP: 先生、今日もお仕事でしょうか？
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 200160090
    Id: 200160090
    CharacterId: 20016
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200160100
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 오늘도 말도 못 하게 바빠….
    MessageJP: 膨大な量の作業が……
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 200160100
    Id: 200160100
    CharacterId: 20016
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200160110
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: '아, 그 마음, 절절히 이해해요. '
    MessageJP: まあ、お気持ちは理解できます
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 200160100
    Id: 200160110
    CharacterId: 20016
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200160110
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ''
    MessageKR: 해치웠다고 생각하면 다시 기어 나오고, 남이 할 거라고 생각한 순간.
    MessageJP: 片付けたと思ったらまた出てくるわ、誰かがやるかと思いきや誰も手を付けないわ
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 200160110
    Id: 200160120
    CharacterId: 20016
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200160120
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ''
    MessageKR: 내게 부메랑처럼 돌아오는 것. 중간관리자가 하는 일이 다 그렇죠. 뭐.
    MessageJP: 大変ですよね、中間管理職
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 200160120
    Id: 200160130
    CharacterId: 20016
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200160130
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 그런데….
    MessageJP: ところで
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 200160130
    Id: 200160140
    CharacterId: 20016
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200160140
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ''
    MessageKR: 뭐, 그럼 오늘 커피는 진한 아메리카노로 부탁드릴게요.
    MessageJP: 今日は苦いのが飲みたい気分ですね
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 200160130
    Id: 200160150
    CharacterId: 20016
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200160140
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 오늘은 어쩐지 쓰디쓴 게 땡기더라구요.
    MessageJP: 濃い目のアメリカーノでお願いします
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 200160140
    Id: 200160160
    CharacterId: 20016
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200160150
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 이로하, 위에서 내가 한 메시지 본 거 맞지?
    MessageJP: イロハ、上にあるメッセージ見てくれた？
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 200160150
    Id: 200160170
    CharacterId: 20016
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200160160
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 네? 그야 물론이죠.
    MessageJP: はい、もちろん
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 200160150
    Id: 200160180
    CharacterId: 20016
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200160160
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 그럼 이따가 뵙겠습니다.
    MessageJP: それではまた後で
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 200160160
    Id: 200160190
    CharacterId: 20016
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 200165
    NextGroupId: 200160170
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 답변이 산뜻해서 이젠 태클 걸 생각도 들지 않아….
    MessageJP: 文脈が読めてないのは私なのかな……
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 200160170
    Id: 200160200
    CharacterId: 20016
    MessageCondition: FavorRankUp
    ConditionValue: 6
    PreConditionGroupId: 200160160
    PreConditionFavorScheduleId: 200165
    FavorScheduleId: 0
    NextGroupId: 200160180
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 하아… 귀찮아.
    MessageJP: やってられません
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 200160180
    Id: 200160210
    CharacterId: 20016
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200160190
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 왜, 이로하. 무슨 일 있어?
    MessageJP: イロハ、どうしたの？
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 200160190
    Id: 200160220
    CharacterId: 20016
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200160200
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 아뇨, 별 건 아니에요…. 그냥….
    MessageJP: いえ、大したことではありませんが……
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 200160190
    Id: 200160230
    CharacterId: 20016
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200160200
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ''
    MessageKR: 사람은 어째서 일을 해야만 살아갈 수 있는가. 하고 잠깐 생각해봤을 뿐이에요.
    MessageJP: なぜ人はこんなに忙しく動かねばならないのだろう、と……
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 200160200
    Id: 200160240
    CharacterId: 20016
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200160210
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ''
    MessageKR: 선생님. 우리가 이렇게까지 하며 살아가는 데에 과연 의미가 있을까요?
    MessageJP: 先生、我々はここまでして生きる意味があるのでしょうか？
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 200160210
    Id: 200160250
    CharacterId: 20016
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200160220
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 갑자기 대화 주제가 무거워졌어! 물론 의미는 있다고 생각하지만!
    MessageJP: 話が急にすごい重くなったけど、あると思うよ！？
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 200160220
    Id: 200160260
    CharacterId: 20016
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200160230
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 정말 정말 하기 싫지만. 그래도 해야만 하겠지요.
    MessageJP: めんどくさいですが、やるしかありませんね……
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 200160220
    Id: 200160270
    CharacterId: 20016
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200160230
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 네, 정말 정말 귀찮지만.
    MessageJP: もう文字を打つのもめんどくさいです
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 200160230
    Id: 200160280
    CharacterId: 20016
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 200166
    NextGroupId: 0
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 어, 음. 힘내….
    MessageJP: が、頑張って……
    MessageCN: ''
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
